services:
  vpnbaz-bridge:
    extends:
      file: docker-compose.base.yml
      service: vpn-template
    container_name: vpnbaz-bridge
    networks:
      ovpn-bridge: {}
      docker-ovpn-vlan:
        ipv4_address: 192.168.0.110
    environment:
      - PROXY_PORT=1080
      - VPN_CONFIG=/etc/openvpn/nl1-typ2.ovpn
    ports:
      - "1080:1080"
    volumes:
      - ./configs/ovpn-vpnbaz:/etc/openvpn:ro,z
      # - ./configs/shared/vpnbaz.auth:/etc/openvpn/auth.txt:ro,z

  eliteping-bridge:
    extends:
      file: docker-compose.base.yml
      service: vpn-template
    container_name: eliteping-bridge
    networks:
      ovpn-bridge: {}
      docker-ovpn-vlan:
        ipv4_address: 192.168.0.120
    environment:
      - PROXY_PORT=1080
      - VPN_CONFIG=/etc/openvpn/ir.de1.e-mix.ir.ovpn
    ports:
      - "1081:1080"
    volumes:
      - ./configs/ovpn-eliteping:/etc/openvpn:ro,z

networks:
  ovpn-bridge:
    driver: bridge
  docker-ovpn-vlan:
    external: true
