services:
  vpnbaz-socks:
    extends:
      file: docker-compose.base.yml
      service: vpn-template
    container_name: ovpn-socks
    environment:
      - PROXY_PORT=1080
      - VPN_CONFIG=/etc/openvpn/smart.ovpn
    ports:
      - "1080:1080"
    volumes:
      - ./configs/ovpn-vpnbaz:/etc/openvpn:ro,z
      # - ./configs/shared/vpnbaz.auth:/etc/openvpn/auth.txt:ro,z
