services:
  vpnbaz-bridge:
    extends:
      file: docker-compose.base.yml
      service: ovpn-template
    container_name: vpnbaz-bridge
    networks:
      ovpn-bridge: {}
      docker-ovpn-vlan:
        ipv4_address: 192.168.0.110
    environment:
      - VPN_CONFIG=/etc/openvpn/nl3-typ2.ovpn
    volumes:
      - ./configs/ovpn-vpnbaz:/etc/openvpn:ro,z
      # - ./configs/shared/vpnbaz.auth:/etc/openvpn/auth.txt:ro,z

  eliteping-bridge:
    extends:
      file: docker-compose.base.yml
      service: ovpn-template
    container_name: eliteping-bridge
    networks:
      ovpn-bridge: {}
      docker-ovpn-vlan:
        ipv4_address: 192.168.0.120
    environment:
      - VPN_CONFIG=/etc/openvpn/nl2.e-mix.ir.ovpn
    volumes:
      - ./configs/ovpn-eliteping:/etc/openvpn:ro,z

networks:
  ovpn-bridge:
    driver: bridge
  docker-ovpn-vlan:
    external: true
