services:
  vpnbaz-bridge:
    extends:
      file: docker-compose.base.yml
      service: ovpn-template
    container_name: vpnbaz-bridge
    networks:
      vpn-test: {}
      docker-ovpn-vlan:
        ipv4_address: 192.168.0.128
    environment:
      - PROXY_PORT=1080
      - VPN_CONFIG=/etc/openvpn/nl3-typ2.ovpn
      - CREDENTIALS=false
    ports:
      - "1080:1080"
    volumes:
      - ./configs/ovpn-vpnbaz:/etc/openvpn:ro,z
      # - ./configs/shared/vpnbaz.auth:/etc/openvpn/auth.txt:ro,z

networks:
  vpn-test:
    driver: bridge
  docker-ovpn-vlan:
    external: true
